<h1>Запретная зона, доступ только авторизированному пользователю</h1>
<h2>Информация выводится из списка файлов</h2>
<table class="table table-bordered">
    <tr>
        <th>Название файла</th>
        <th>Фотография</th>
        <th>Действия</th>
    </tr>
    <?php foreach($this->files as $file): ?>
        <tr>
            <td><?= $file['name']; ?></td>
            <td>
                <img src="<?= $file['name']; ?>" alt="">
            </td>
            <td>
                <a href="/file/destroy/?id=<?= $file['id']; ?>">Удалить аватарку пользователя</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>