<?php if (!$this->user): ?>
    <div class="form-container">
        <form class="form-horizontal" action="/auth" method="post">

            <?php
            if ($this->errors) {
                foreach ($this->errors as $error) {
                    echo '<p>' . $error . '</p>';
                }
            }
            ?>

            <input type="hidden" name="auth" value="1">
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Логин (email)</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="inputEmail3" name="login" placeholder="Логин"
                           value="<?= $this->login; ?>" required>
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">Пароль</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="inputPassword3" name="password"
                           placeholder="Пароль" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Войти</button>
                    <br><br>
                    Нет аккаунта? <a href="/register">Зарегистрируйтесь</a>
                </div>
            </div>
        </form>
    </div>
<?php else: ?>
    <h1>Вы успешно авторизованы!</h1>
    <a href="/logout">Разлогиниться</a>
<?php endif;?>