<h1>Запретная зона, доступ только авторизированному пользователю</h1>
<h2>Информация выводится из базы данных</h2>

<br>
<a href="/user/create" class="btn btn-success">Добавить пользователя</a>
<br>
<br>
<table class="table table-bordered">
    <tr>
        <th>Пользователь(логин)</th>
        <th>Имя</th>
        <th>возраст</th>
        <th>описание</th>
        <th>Фотография</th>
        <th>Действия</th>
    </tr>
    <?php foreach ($this->users as $user): ?>
        <tr>

            <td><?= $user['email']; ?></td>
            <td><?= $user['name']; ?></td>
            <td><?= $user['age']; ?><br><?= $user['adult_status']; ?></td>
            <td><?= $user['description']; ?></td>
            <td>
                <?php if (isset($user['images'][0]['name'])): ?>
                    <img src="<?= $user['images'][0]['name']; ?>" alt="">
                <?php endif; ?>
            </td>
            <td>
                <a href="/user/update/?user_id=<?= $user['id']; ?>" class="btn btn-primary">Редактировать пользователя</a>
                <br>
                <br>
                <a href="/user/destroy/?id=<?= $user['id']; ?>" class="btn btn-danger">Удалить пользователя</a>
                <br>
                <br>
                <br>
                <form action="/change-photo" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="user_id" value="<?= $user['id']; ?>">
                    <div class="form-group">
                        <input type="file" name="photo" class="form-control" id="photo" placeholder="Фотография"
                               accept=".png, .jpg, .jpeg" required>
                        <button type="submit" class="btn btn-default">Изменить фото</button>
                    </div>
                </form>

            </td>
        </tr>
    <?php endforeach; ?>
</table>