<?php

if ($this->user) {
    $user = $this->user->toArray();
    $images = $user['images'];
    if (!empty($images)) {
        $image = reset($images);
    }
}
?>

<div class="form-container">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">

        <?php
        if ($this->errors) {
            foreach ($this->errors as $error) {
                echo '<p>' . $error . '</p>';
            }
        }
        ?>

        <input type="hidden" name="update" value="1">
        <input type="hidden" name="user_id" value="<?= $user['id']; ?>">
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Логин (email)</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="inputEmail3" name="login" placeholder="Логин"
                       value="<?= $user['email']; ?>" required>
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail5" class="col-sm-2 control-label">Имя</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputEmail5" name="name" placeholder="Имя"
                       value="<?= $user['name']; ?>" required>
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail4" class="col-sm-2 control-label">Возраст</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="inputEmail4" name="age" placeholder="Возраст"
                       value="<?= $user['age']; ?>" required>
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail4" class="col-sm-2 control-label">Описание</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputEmail4" name="description" placeholder="Описание"
                       value="<?= $user['description']; ?>" required>
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail6" class="col-sm-2 control-label">Аватар</label>
            <div class="col-sm-10">
                <input type="file" class="form-control" id="photo" name="photo" placeholder="Аватар"
                       accept=".png, .jpg, .jpeg" required>

                <? if (isset($image)): ?>
                    <img src="<?= $image['name']; ?>" alt="">
                <? endif; ?>
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">Пароль</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword3" name="password" placeholder="Пароль"
                       required>
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword4" class="col-sm-2 control-label">Пароль (Повтор)</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword4" name="password_confirm"
                       placeholder="Пароль" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Обновить данные пользователя</button>
            </div>
        </div>
    </form>
</div>